name = "cloud-probe-worker"
main = "src/index.js"
compatibility_date = "2024-06-19"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "${RATE_LIMIT_KV_ID}"

[env.production]
workers_dev = false
route = "*.probe.homeall.com/*"
zone_id = "${ZONE_ID}"

  [[env.production.kv_namespaces]]
  binding = "RATE_LIMIT_KV"
  id = "${RATE_LIMIT_KV_ID}"

[dev]
port = 8787