name = "cloud-probe-worker"
main = "src/index.js"
compatibility_date = "2024-06-18"

[build]
command = "npm install"

[build.upload]
format = "service-worker"

[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes for scheduled tasks

# KV Namespace for rate limiting and metrics
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "${RATE_LIMIT_KV_ID}"

# Uncomment and configure these for production
[env.production]
workers_dev = true
# route = ""
# zone_id = ""

[dev]
port = 8787
