name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  RATE_LIMIT_KV_ID: ${{ secrets.RATE_LIMIT_KV_ID }}
  API_PROBE_TOKEN: ${{ secrets.API_PROBE_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        env:
          NODE_ENV: test

      - name: Deploy to Cloudflare Workers
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
          environment: 'production'
        env:
          RATE_LIMIT_KV_ID: ${{ secrets.RATE_LIMIT_KV_ID }}
          API_PROBE_TOKEN: ${{ secrets.API_PROBE_TOKEN }}
