name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  RATE_LIMIT_KV_ID: ${{ secrets.RATE_LIMIT_KV_ID }}
  API_PROBE_TOKEN: ${{ secrets.API_PROBE_TOKEN }}
  ZONE_ID: ${{ secrets.ZONE_ID }}
  PROBE_DOMAIN: ${{ secrets.PROBE_DOMAIN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Generate wrangler.toml from template
        run: |
          cat .wrangler.toml.template \
            | sed "s|\${CF_ACCOUNT_ID}|${{ secrets.CF_ACCOUNT_ID }}|g" \
            | sed "s|\${RATE_LIMIT_KV_ID}|${{ secrets.RATE_LIMIT_KV_ID }}|g" \
            | sed "s|\${ZONE_ID}|${{ secrets.ZONE_ID }}|g" \
            | sed "s|\${PROBE_DOMAIN}|${{ secrets.PROBE_DOMAIN }}|g" \
            > wrangler.toml
            
      - name: Show wrangler.toml non-secret info
        run: |
          echo "Sections present in wrangler.toml:"
          grep '^\[' wrangler.toml || true
          echo "Name: $(grep '^name =' wrangler.toml || true)"
          echo "Main: $(grep '^main =' wrangler.toml || true)"
          echo "Account: $(grep '^account_id =' wrangler.toml | cut -c1-20)..."
          echo "Route: $(grep '^route =' wrangler.toml || true)"

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        env:
          NODE_ENV: test

      - name: Deploy to Cloudflare Workers
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy
          environment: 'production'
        env:
          RATE_LIMIT_KV_ID: ${{ secrets.RATE_LIMIT_KV_ID }}
          API_PROBE_TOKEN: ${{ secrets.API_PROBE_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
