name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Generate metadata
        id: meta
        run: |
          echo "short_sha=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Generate wrangler.toml from template
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          RATE_LIMIT_KV_ID: ${{ secrets.RATE_LIMIT_KV_ID }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          PROBE_DOMAIN: ${{ secrets.PROBE_DOMAIN }}
          API_PROBE_TOKEN: ${{ secrets.API_PROBE_TOKEN }}
          VERSION: ${{ github.ref_name }}
          GIT_COMMIT: ${{ steps.meta.outputs.short_sha }}
          BUILD_TIME: ${{ steps.meta.outputs.build_date }}
        run: envsubst < wrangler.toml.template > wrangler.toml

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        env:
          NODE_ENV: test

      - name: Deploy to Cloudflare Workers
#        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy
          environment: 'production'
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}


